config/routes.rb
Ph3::Application.routes.draw do
  get "rpc/call"

  get "home/index"

  match "/rpc" => 'rpc#call'

  match "/ddir/" => 'dir#index', :constraints => {:host => /^(ipacs.*|www2.*|www.*|physcon.ru)/} 
  match "/ddir/c(:category)t(:topic).html" => 'dir#any', :constraints => {:host => /^(ipacs.*|www2.*|www.*|physcon.ru)/, :topic => /\d+/, :category => /\d+/}

  match "/ipacs/" => 'old_ipacs#index', :constraints => {:host => /^(ipacs.*|www2.*|www.*|physcon.ru)/} 
  match "/ipacs/:name.html" => 'old_ipacs#any', :constraints => {:host => /^(ipacs.*|www2.*|www.*|physcon.ru)/} 

  root :to => 'ipacs#index', :constraints => {:host => /^(ipacs.*|www2.*|www.*|physcon.ru|s4.physcon.ru)/}
  match "/:action" => 'ipacs', :constraints => {:host => /^(ipacs.*|www2.*|www.*|physcon.ru|s4.physcon.ru)/} 

constraints :subdomain => "cap.s4" do
	match '/read' => redirect('http://lib.physcon.ru/doc?id=29e59dce4f11')
	match '/submit' => redirect('http://coms.physcon.ru/conf/12/')
	root :to => 'cap#index'
	match "/:action" => 'cap'
end
constraints :subdomain => "cap" do
	match '/read' => redirect('http://lib.physcon.ru/doc?id=29e59dce4f11')
	match '/submit' => redirect('http://coms.physcon.ru/conf/12/')
	root :to => 'cap#index'
	match "/:action" => 'cap'
end

  root :to => 'lib#index', :constraints => {:host => /^(lib.*|lib2.*|lib.s4.*)/}
  match "/:action" => 'lib', :constraints => {:host => /^(lib.*|lib2.*|lib.s4.*)/} 

  root :to => 'admin#index', :constraints => {:host => /^(admin.*)/}

constraints :subdomain => "admin2" do
  scope :module => "admin", as: 'admin' do
    match '/lib/' => 'lib#index'
    resources :news, :as => :news_items
  end
end

constraints :subdomain => "admin" do
  scope :module => "admin", as: 'admin' do
    match '/lib/' => 'lib#index'
    resources :news, :as => :news_items
  end
end

end

app/controllers/admin/news_controller.rb
class Admin::NewsController < ApplicationController
	def index
		@data = Physcon::App.model.pg.query_inject [], "SELECT newsid, title, content, addtime FROM newsschema.news ORDER BY addtime DESC" do |acc, row|
			acc << row
			acc
		end
#		render :text => @data.inspect
	end
	def new
	end
	def create
		Physcon::App.model.pg.query "insert into newsschema.news (title, content) values ('%s', '%s')", params[:news]['title'], params[:news]['content']
	#	render text: params[:news].inspect
		redirect_to admin_news_items_path
	end
	def show
	end
	def edit
		@id = params['id']
		@data = Physcon::App.model.pg.query_one "select * from newsschema.news where newsid='%s'", @id
		#render text: params.inspect
	end
	def update
		Physcon::App.model.pg.query "update newsschema.news set title='%s', content='%s' where newsid='%s'", params[:news]['title'], params[:news]['content'], params['id']
	#	render text: params.inspect
		redirect_to admin_news_items_path
	end
	def destroy
		#render text: params[:news].inspect
		Physcon::App.model.pg.query "DELETE FROM newsschema.news WHERE newsid='%s'", params['id']
		#render text: params.inspect
		redirect_to admin_news_items_path
	end
#	def lib
#	end
end

app/views/admin/news/edit.html.haml
-content_for :page_title, 'Edit news item'
-content_for :page_id, 'news'

-set_content_for :content do
 .page
  %h2 Edit news item
  =#@data.inspect
  =link_to 'Back', admin_news_items_path
  = form_for :news, url: admin_news_item_path(@id), method: :put do |f|
   %p
    = f.label :title
    %br
    = f.text_field :title, size: 120, value: @data['title']
   %p
    = f.label :content
    %br
    = f.text_area :content, :size => "120x20", value: @data['content']
   %p
    = f.submit

  %hr
  =button_to 'Delete', admin_news_item_path(@id), confirm: 'Are you sure?', method: :delete, onclick: "if(!confirm('Are you sure?')) return false"


-render :file => 'admin/layout'

app/views/admin/news/index.html.haml
-content_for :page_title, 'News admin'
-content_for :page_id, 'news'

-set_content_for :content do
 .page
  %h2 News admin
  =# link_to 'New item', new_news_item_path
  = link_to 'New item', new_admin_news_item_path
  =# link_to 'New item', new_news_path
  %table{border: 1}
   %tr
    %th{rowspan: 2}
     Id
     %br
     Time
    %th Title
   %tr
    %th Text
   -@data.each do |row|
    %tr
     %td{rowspan: 2}
      = row['newsid']
      %br
      = DateTime.parse(row['addtime']).strftime('%d.%m.%Y')
      %br
      =#link_to 'Show', admin_news_item_path(row['newsid'])
      =link_to 'Edit', edit_admin_news_item_path(row['newsid'])
      =#link_to 'Delete', admin_news_item_path(row['newsid']), confirm: 'Are you sure?', method: :delete
      =#button_to 'Delete', admin_news_item_path(row['newsid']), confirm: 'Are you sure?', method: :delete
     %td= row['title']
    %tr
     %td= row['content']


-render :file => 'admin/layout'

app/views/admin/news/new.html.haml
-content_for :page_title, 'New news item'
-content_for :page_id, 'news'

-set_content_for :content do
 .page
  %h2 New news item
  =link_to 'Back', admin_news_items_path
  = form_for :news, url: admin_news_items_path do |f|
   %p
    = f.label :title
    %br
    = f.text_field :title, size: 120
   %p
    = f.label :content
    %br
    = f.text_area :content, :size => "120x20"
   %p
    = f.submit



-render :file => 'admin/layout'

app/views/admin/news/show.html.haml
-content_for :page_title, 'Show news item'
-content_for :page_id, 'news'

-set_content_for :content do
 .page
  %h2 Show news item
  =link_to 'Back', admin_news_items_path


-render :file => 'admin/layout'